### ISSUE TITLE
Build fails with freertos version greater than 10.4.0

### ISSUE THREAD

**Issue by spookee0** [IntergatedCircuits/freertos-mcpp#1]
From freertos version 10.4.0 (https://github.com/FreeRTOS/FreeRTOS-Kernel/releases/tag/V10.4.0-kernel-only) functions
    **xTaskGenericNotify(...)**  and **xTaskGenericNotifyFromISR(...)** accept  new arg **UBaseType_t uxIndexToNotify**

**Comment by benedekkupper** [comment]
Thanks for the fix :) Feel free to add issues if you have suggestions to improve this project.
